modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "amblekit"
version = "${version}"
displayName = "AmbleKit"
authors = "Loqor, Theo"
description = '''
AmbleKit is a mod that provides a set of tools and utilities for AmbleLabs' assorted Minecraft mods (this one is for Forge!!).
'''
#logoFile = ""

[[dependencies.amblekit]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.amblekit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
